### ISSUE TITLE
Abnormal button shape

### ISSUE THREAD

**Issue by surfishs** [AmyMialeeMods/elegantarmour#1]
On the start screen, open the settings page, I don't think this button should be indented. Please fix it.
![image](https://github.com/AmyMialeeMods/elegantarmour/assets/96485650/04448c63-f70a-40f2-9eb0-387a56e161b4)
![image](https://github.com/AmyMialeeMods/elegantarmour/assets/96485650/86b8629a-abbd-41a7-b6ba-7e732eef2665)

**Comment by AmyMialee** [comment]
Fixed 1.0.2
